times = ('atletico', 'atletico PR','internacional','gremio','atletico GO','vasco da gama','bahia','são paulo','sport recife o melhor','flamengo','palmeiras','bragantino SP',' ceara SC','botafogo','corinthians','goias','fluminense','santos','fortaleza',' coritiba')
ordem_alfabetica = ('atletico', 'atletico PR','atletico GO','bahia','bragantino SP','botafogo',' ceara SC','corinthians',' coritiba','flamengo','fluminense','fortaleza','goias','gremio','internacional','palmeiras','santos','são paulo','sport recife o melhor','vasco da gama',)
print('os cinco primeiros times colocados são {}'.format(times[0:5]))
print('os quatro ultimos times colocados são {}'.format(times[16:]))
print('os times em ordem alfabetica são {}'.format(ordem_alfabetica))
print('a chapecoense não está na serie "a"')